# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  nerdFontsVersion: "3"
  showFileTree: true
  showRandomTip: false
  border: single
  filterMode: fuzzy
os:
  editPreset: nvim
git:
  autoFetch: false
  autoRefresh: true
  externalDiffCommand: "difft --color=always"
  mainBranches:
    - main
    - master
  log:
    order: topo-order
    showGraph: always
