require "user.keymaps"
require "user.options"
require "user.plugins"

require "user.treesitter"
require "user.cmp"
require "user.lsp"
require "user.neotree"
require "user.lspsaga"

require "user.autopairs"
require "user.colorscheme"
require "user.go"
require "user.telescope"
require "user.trouble"
require "user.vim-plugins"
require "user.autocommands"
require "user.illuminate"
require "user.setups"
require "user.gitsigns"
