require "user.keymaps"
require "user.options"
require "user.plugins"

require "user.treesitter"
require "user.cmp"
require "user.lsp"
require "user.nvim-tree"
require "user.lspsaga"

require "user.autopairs"
require "user.bufferline"
require "user.colorscheme"
require "user.go"
require "user.lualine"
require "user.telescope"
require "user.vim-plugins"
require "user.autocommands"
require "user.illuminate"
