[terminal.shell]
program = "Arch"

[general]
# import = ["gruvbox.toml"]

[env]
TERM = "screen-256color"

[terminal]
osc52 = "CopyPaste"

[window]
dimensions = { columns = 120, lines = 45 }
padding = { x = 1, y = 1 }
decorations = "full"
dynamic_title = false
# opacity = 0.9

[font]
# normal = { family = "Recursive Nerd Font", style = "Regular" }
# size = 11
# offset = { x = 1, y = 1 }
normal = { family = "Consolas Nerd Font", style = "Regular" }
# normal = { family = "IosevkaTaiga Nerd Font", style = "Regular" }
size = 12
offset = { x = 1, y = 1 }

[keyboard]
bindings = [
    { action = "Paste", key = "V", mods = "Alt" },
    { action = "Copy", key = "C", mods = "Alt" },
]
