[env]
TERM = "screen-256color"

[terminal]
osc52 = "CopyPaste"

[window]
dimensions = { columns = 180, lines = 60 }
padding = { x = 1, y = 1 }
decorations = "full"
dynamic_title = false
option_as_alt = "Both"

[font]
# normal = { family = "Recursive Nerd Font", style = "Regular" }
# size = 14
# offset = { x = 1, y = 1 }
normal = { family = "Consolas Nerd Font", style = "Regular" }
size = 16
offset = { x = 1, y = 3 }

[keyboard]
bindings = [
    { action = "Paste", key = "V", mods = "Alt" },
    { action = "Copy", key = "C", mods = "Alt" },
    # Support for CSI u mode
    # { chars = "\u001b[13;5u", key = "Return", mods = "Control" },
    # { chars = "\u001b[104;5u", key = "H", mods = "Control" },
    # { chars = "\u001b[105;5u", key = "I", mods = "Control" },
    # { chars = "\u001b[106;5u", key = "J", mods = "Control" },
    # { chars = "\u001b[109;5u", key = "M", mods = "Control" },

    # (macOS only)
    # { action = "ReceiveChar", key = "K", mode = "~Vi|~Search", mods = "Command" },
    # { action = "ReceiveChar", key = "Key0", mods = "Command" },
    # { action = "ReceiveChar", key = "Equals", mods = "Command" },
    # { action = "ReceiveChar", key = "Plus", mods = "Command" },
    # { action = "ReceiveChar", key = "NumpadAdd", mods = "Command" },
    # { action = "ReceiveChar", key = "Minus", mods = "Command" },
    # { action = "ReceiveChar", key = "NumpadSubtract", mods = "Command" },
    # { action = "ReceiveChar", key = "V", mods = "Command" },
    # { action = "ReceiveChar", key = "C", mods = "Command" },
    # { action = "ReceiveChar", key = "C", mode = "Vi|~Search", mods = "Command" },
    # { action = "ReceiveChar", key = "H", mods = "Command" },
    # { action = "ReceiveChar", key = "H", mods = "Command|Alt" },
    # { action = "ReceiveChar", key = "M", mods = "Command" },
    # { action = "ReceiveChar", key = "Q", mods = "Command" },
    # { action = "ReceiveChar", key = "W", mods = "Command" },
    # { action = "ReceiveChar", key = "N", mods = "Command" },
    # { action = "SpawnNewInstance", key = "N", mods = "Command|Shift" },
    # { action = "ReceiveChar", key = "F", mods = "Command|Control" },
    # { action = "ReceiveChar", key = "F", mode = "~Search", mods = "Command" },
    # { action = "ReceiveChar", key = "B", mode = "~Search", mods = "Command" },
    # { action = "ReceiveChar", key = "B", mods = "Command" },

    # https://github.com/alacritty/alacritty/issues/93
    # { chars = "\u001b-", key = "Minus", mods = "Alt" },
    # { chars = "\u001b=", key = "Equals", mods = "Alt" },
    # { chars = "\u001b+", key = "Plus", mods = "Alt" },
    # { chars = "\u001b[", key = "LBracket", mods = "Alt" },
    # { chars = "\u001b]", key = "RBracket", mods = "Alt" },
    # { chars = "\u001b{", key = "LBracket", mods = "Alt|Shift" },
    # { chars = "\u001b}", key = "RBracket", mods = "Alt|Shift" },

    # # https://github.com/alacritty/alacritty/issues/62
    # { chars = "\u001ba", key = "A", mods = "Alt" },
    # { chars = "\u001bb", key = "B", mods = "Alt" },
    # { chars = "\u001bd", key = "D", mods = "Alt" },
    # { chars = "\u001be", key = "E", mods = "Alt" },
    # { chars = "\u001bf", key = "F", mods = "Alt" },
    # { chars = "\u001bg", key = "G", mods = "Alt" },
    # { chars = "\u001bh", key = "H", mods = "Alt" },
    # { chars = "\u001bi", key = "I", mods = "Alt" },
    # { chars = "\u001bj", key = "J", mods = "Alt" },
    # { chars = "\u001bk", key = "K", mods = "Alt" },
    # { chars = "\u001bl", key = "L", mods = "Alt" },
    # { chars = "\u001bm", key = "M", mods = "Alt" },
    # { chars = "\u001bn", key = "N", mods = "Alt" },
    # { chars = "\u001bo", key = "O", mods = "Alt" },
    # { chars = "\u001bp", key = "P", mods = "Alt" },
    # { chars = "\u001bq", key = "Q", mods = "Alt" },
    # { chars = "\u001br", key = "R", mods = "Alt" },
    # { chars = "\u001bs", key = "S", mods = "Alt" },
    # { chars = "\u001bt", key = "T", mods = "Alt" },
    # { chars = "\u001bu", key = "U", mods = "Alt" },
    # { chars = "\u001bw", key = "W", mods = "Alt" },
    # { chars = "\u001bx", key = "X", mods = "Alt" },
    # { chars = "\u001by", key = "Y", mods = "Alt" },
    # { chars = "\u001bz", key = "Z", mods = "Alt" },
    # { chars = "\u001bA", key = "A", mods = "Alt|Shift" },
    # { chars = "\u001bB", key = "B", mods = "Alt|Shift" },
    # { chars = "\u001bC", key = "C", mods = "Alt|Shift" },
    # { chars = "\u001bD", key = "D", mods = "Alt|Shift" },
    # { chars = "\u001bE", key = "E", mods = "Alt|Shift" },
    # { chars = "\u001bF", key = "F", mods = "Alt|Shift" },
    # { chars = "\u001bG", key = "G", mods = "Alt|Shift" },
    # { chars = "\u001bH", key = "H", mods = "Alt|Shift" },
    # { chars = "\u001bI", key = "I", mods = "Alt|Shift" },
    # { chars = "\u001bJ", key = "J", mods = "Alt|Shift" },
    # { chars = "\u001bK", key = "K", mods = "Alt|Shift" },
    # { chars = "\u001bL", key = "L", mods = "Alt|Shift" },
    # { chars = "\u001bM", key = "M", mods = "Alt|Shift" },
    # { chars = "\u001bN", key = "N", mods = "Alt|Shift" },
    # { chars = "\u001bO", key = "O", mods = "Alt|Shift" },
    # { chars = "\u001bP", key = "P", mods = "Alt|Shift" },
    # { chars = "\u001bQ", key = "Q", mods = "Alt|Shift" },
    # { chars = "\u001bR", key = "R", mods = "Alt|Shift" },
    # { chars = "\u001bS", key = "S", mods = "Alt|Shift" },
    # { chars = "\u001bT", key = "T", mods = "Alt|Shift" },
    # { chars = "\u001bU", key = "U", mods = "Alt|Shift" },
    # { chars = "\u001bV", key = "V", mods = "Alt|Shift" },
    # { chars = "\u001bW", key = "W", mods = "Alt|Shift" },
    # { chars = "\u001bX", key = "X", mods = "Alt|Shift" },
    # { chars = "\u001bY", key = "Y", mods = "Alt|Shift" },
    # { chars = "\u001bZ", key = "Z", mods = "Alt|Shift" },
    # { chars = "\u001b1", key = "Key1", mods = "Alt" },
    # { chars = "\u001b2", key = "Key2", mods = "Alt" },
    # { chars = "\u001b3", key = "Key3", mods = "Alt" },
    # { chars = "\u001b4", key = "Key4", mods = "Alt" },
    # { chars = "\u001b5", key = "Key5", mods = "Alt" },
    # { chars = "\u001b6", key = "Key6", mods = "Alt" },
    # { chars = "\u001b7", key = "Key7", mods = "Alt" },
    # { chars = "\u001b8", key = "Key8", mods = "Alt" },
    # { chars = "\u001b9", key = "Key9", mods = "Alt" },
    # { chars = "\u001b0", key = "Key0", mods = "Alt" },
    # { chars = "\u0000", key = "Space", mods = "Control" },
    # { chars = "\u001b`", key = "`", mods = "Alt" },
    # { chars = "\u001b~", key = "~", mods = "Alt|Shift" },
    # { chars = "\u001b.", key = "Period", mods = "Alt" },
    # { chars = "\u001b>", key = "Period", mods = "Alt|Shift" },
    # { chars = "\u001b<", key = "Comma", mods = "Alt|Shift" },
    # { chars = "\u001b_", key = "Minus", mods = "Alt|Shift" },
    # { chars = "\u001b#", key = "Key3", mods = "Alt|Shift" },
    # { chars = "\u001b%", key = "Key5", mods = "Alt|Shift" },
    # { chars = "\u001b^", key = "Key6", mods = "Alt|Shift" },
    # { chars = "\u001b*", key = "Key8", mods = "Alt|Shift" },
    # { chars = "\u001b\\", key = "Backslash", mods = "Alt" },
    # { chars = "\u001b|", key = "Backslash", mods = "Alt|Shift" },
    # { chars = "\u001b/", key = "Slash", mods = "Alt" },
]
